### ISSUE TITLE
Allow always-multiline maps

### ISSUE THREAD

**Issue by gfredericks** [greglook/puget#11]
Would it be difficult to add an option that forces map keys to always be on different lines?

This sort of behavior is the default for some tools, such as [jq](http://stedolan.github.io/jq/):

```
$ echo '{"foo":1,"bar":2}' | jq .
{
  "bar": 2,
  "foo": 1
}
```

**Comment by greglook** [comment]
Closing as stale - feel free to reopen if the above suggestions don't work and you still need this.
