### ISSUE TITLE
Any mechanism for dispatching on :type metadata?

### ISSUE THREAD

**Issue by gfredericks** [greglook/puget#13]
In a few different contexts I've taken advantage of the fact that clojure's `print-method` is a multimethod that allows me to customize any `IObj` by simply setting its `:type` metadata. E.g., I use it [here](https://github.com/gfredericks/repl-utils/blob/master/src/com/gfredericks/repl.clj#L63) to cause a var to print with pertinent information.

Using puget at my repl disrupts this behavior, and since `TaggedValue` is a protocol I can't use it to extend objects this way.

So I have two questions:

1. Is there some other way for getting metadata-level custom printing that I'm missing? Or is converting `TaggedValue` to a multimethod the only sensible way to do this?
2. Is the change in the previous point something you would be interested in, or should I just use a personal fork of the project?

**Comment by greglook** [comment]
I've been playing around with this recently, I'll push a branch soon with some test changes.

**Comment by gfredericks** [comment]
Cool; I had played around with it too but I think I didn't end up changing my normal dev configuration because of the plugin/dependency two-step deployment hassle. But I think it seemed to work.
