### ISSUE TITLE
cannot work with core.cache

### ISSUE THREAD

**Issue by hikoz** [greglook/puget#22]
puget.print/pprint failes when tried to print core.cache object.
It because you cannot sort Cache type.

You can reproduce with below.
```clojure
(require '[leiningen.exec :refer [deps])
(deps '[[org.clojure/core.cache "0.6.4"]
        [mvxcvi/puget "0.8.1"]])
(require '[clojure.core.cache :as cache])
(require '[puget.printer :as puget])
(def c (cache/ttl-cache-factory {:a 1}))
(prn c)
(puget/cprint c)
```

**Comment by greglook** [comment]
Hmm, I'll take a look. As a workaround, you could use the `:escape-types` option to avoid pretty-printing these.

**Comment by greglook** [comment]
With 0.9.0 you can specify a custom print handler for `core.cache` objects to get around this behavior.
