### ISSUE TITLE
sort-keys missing from 0.9.0

### ISSUE THREAD

**Issue by brandonbloom** [greglook/puget#25]
Looks like the latest upgrades for Clojure 1.7 and the new Fipp broke this.

sort-keys was originally discussed here: https://github.com/greglook/puget/issues/12

In the past, the default was "always sort", but for interactive use, I think something around the height of one terminal screen (100 to 200) is a better default.

**Comment by greglook** [comment]
Ahh, I had a change renaming this to `:sort-mode`, but on further thought I think I'll change it back to `:sort-keys` instead. Numeric is probably a better default too.

**Comment by greglook** [comment]
Fixed in 8b1b38dbe23ad6513d1e0a3e42273916f4512a4d as part of release 0.9.1.

**Comment by brandonbloom** [comment]
Oops, sorry, I should have read the change-log. I didn't realize it was simply renamed! Anyway, thanks for the prompt response and the change to the default.
