### ISSUE TITLE
Lazy seqs don't print in 0.9.0

### ISSUE THREAD

**Issue by brandonbloom** [greglook/puget#26]
You get something like this: `#<clojure.lang.LazySeq@4415f253 pending>`

**Comment by greglook** [comment]
Ahh I remember changing a test dealing with LazySeqs. Will add a special handler for these.

**Comment by greglook** [comment]
Fixed in cf4af760d05b4e80bc5a9c8677d92a8c00a9423c as part of 0.9.1.

**Comment by brandonbloom** [comment]
Code looks good & verified working over here. Thanks!
