### ISSUE TITLE
Print namespaced maps using #:

### ISSUE THREAD

**Issue by aengelberg** [greglook/puget#36]
In Clojure 1.9, Clojure's default pretty printing automatically uses the new `#:prefix{:key ...}` syntax when all keys in a map are keywords and share a namespace.
```clojure
user=> (pr-str {:a/b 1})
"#:a{:b 1}"
user=> (pr-str {:a/b 1 :b/c 2})
"{:a/b 1, :b/c 2}"
user=> (puget/render-str (puget/canonical-printer) {:a/b 1})
"{:a/b 1}"
```
It would be cool if puget printers supported this because it would more compactly express the maps in some cases. Making this behavior "opt-in" would probably be best, to ensure that the canonical printer (by default) does not start emitting data differently unless you explicitly tell it to. Something like:
```clojure
(puget/canonical-printer {:namespaced-maps true})
```

**Comment by greglook** [comment]
Yep, I had this thought too after the 1.9 upgrade. The pretty printer should definitely support this. I'm not sure that adding it to the canonical printer is a good idea, since the keyword dispatch is _Clojure_ reader sugar and not present in the EDN spec.

**Comment by aengelberg** [comment]
Ah. You're right that it isn't in the EDN spec, though oddly, the Clojure EDN reader does accept it:
```clojure
user=> (clojure.edn/read-string "#:a{:b 1}")
{:a/b 1}
```

**Comment by gfredericks** [comment]
to avoid generating too much horizontal whitespace, I'd suggest that the prefix sometimes or always go on its own line.

**Comment by aengelberg** [comment]
I think that would make sense if and only if the data inside the map spanned multiple lines.

**Comment by gfredericks** [comment]
agreed; I will retroactively have meant that by the word "sometimes"

**Comment by gfredericks** [comment]
although you could argue that if you have a maximally-long-single-lined-map that needs to be prefixed by a very long namespace, doing two lines is better

and perhaps I _will_ argue that

**Comment by greglook** [comment]
Sounds good to me - fipp should handle the line-breaking when the total line size exceeds a certain amount.
