### ISSUE TITLE
Sorted collections are re-sorted

### ISSUE THREAD

**Issue by gfredericks** [greglook/puget#37]
This collection prints as `#{1 2 3}` but seqs as `(3 2 1)`: `(sorted-set-by > 1 2 3)`.

I have twice in my life lost fifteen minutes trying to figure out why my sorted collection wasn't behaving the way I thought it should.

The documentation states that _all_ collections get sorted when that option is turned on, but I feel like it would be better if only applied to unsorted collections.

**Comment by greglook** [comment]
Makes sense to me for the pretty-printer. The canonical printer should still sort according to the intrinsic value ordering I think, unless you have specific thoughts as to why not.

**Comment by gfredericks** [comment]
I've never used or looked at the canonical printer, so I have no opinions
about it

**Comment by randomizedthinking** [comment]
I encountered the same issue today. Below is a simple demonstration:

    (defn order-by-y-then-x [k1 k2]
      (let [[x1 y1] k1 [x2 y2] k2]
        (compare [y1 x1] [y2 x2])))
    
    (def a-sorted-map
      (into (sorted-map-by order-by-y-then-x)
            {[2 8] :a [3 4] :b [6 7] :c}))
    
    (clojure.pprint/pprint a-sorted-map)  ;; {[3 4] :b, [6 7] :c, [2 8] :a}
    (puget.printer/pprint a-sorted-map)   ;; {[2 8] :a, [3 4] :b, [6 7] :c}

We can see that the canonical printer respects the order as specified by the variable. It makes sense...

**Comment by greglook** [comment]
Fix released in 1.1.0.
