### ISSUE TITLE
Java object cprint does not match README screenshot

### ISSUE THREAD

**Issue by lread** [greglook/puget#48]
Hey there!

While working on unit tests for #44, I noticed that:

```clojure
(require '[puget.printer :as printer])
(printer/cprint (java.util.Currency/getInstance "USD"))
``` 

I get the following result:
![image](https://user-images.githubusercontent.com/967328/66274466-0aa19c00-e84d-11e9-827d-547b7558f98a.png)

Which does not match the format shown in the README screenshot:
![image](https://user-images.githubusercontent.com/967328/66274420-87804600-e84c-11e9-8bee-485ad09e774f.png)

I don't know what the expected/desired behavior is, perhaps the README screenshot just needs an update?

**Comment by greglook** [comment]
Yeah, I added the object ID to object printers because it's useful to be able to distinguish distinct instances of a class that would otherwise render identically. I'm somewhat ambivalent about updating the screenshot, it's more meant to give a sense of what the library does than be 100% accurate.
