### ISSUE TITLE
GraalVM binary

### ISSUE THREAD

**Issue by borkdude** [greglook/puget#53]
Are you interested in creating a GraalVM binary much like zprint has done, so you can use this lib from the command line?

I would be happy to do it myself if you're not interested in it. Not sure if I could use the name `puget` for that binary?

The use case for this would be to pipe any program that outputs EDN or Clojure code into that binary to get colorized output.

Also see https://github.com/borkdude/babashka/issues/620

**Comment by greglook** [comment]
I sort of did this already with [edn-tool](https://github.com/greglook/edn-tool), though I haven't worked on that in a bit. I was planning to make it more of a `jq` equivalent, but abandoned that when I found out about [jet](https://github.com/borkdude/jet). 😉
